---

# Primary configuration. 

homeassistant:
  name: Home
  unit_system: metric
  time_zone: Australia/Melbourne
  longitude: !secret hass_longitude
  latitude: !secret hass_latitude
  elevation: !secret hass_elevation
  customize: !include customize.yaml



# Basic components.

discovery:

frontend:

history:

logbook:

sun:

updater:



# Advanced components.

automation: !include_dir_list automation

camera: !include components/camera.yaml

climate: !include components/climate.yaml

cover: !include components/cover.yaml

device_tracker: !include components/device_tracker.yaml

group: !include components/group.yaml

http: !include components/http.yaml

light: !include components/light.yaml

mqtt: !include components/mqtt.yaml

# scene: !include_dir_list scenes

sensor: !include components/sensor.yaml

# script: !include_dir_list scripts

zwave: !include components/zwave.yaml