---

# UniFi CloudKey
- platform: unifi
  host: !secret unifi_ip
  username: !secret unifi_user
  password: !secret unifi_pass
  track_new_devices: no
  interval_seconds: 12
  consider_home: 180

- platform: owntracks
