---

# Bureau of Meteorology (BOM)
- platform: bom
  zone_id: IDV60801
  wmo_id: 94852
  monitored_conditions:
    - air_temp

# Daikin
- platform: daikin
  ipaddress: !secret daikin_ip

# Speedtest.net
#- platform: speedtest
#  minute:
#    - 0
#    - 30
#  monitored_conditions:
#    - ping
#    - download
#    - upload