---

alias: 'Turn on entry light at sun set'
trigger:
  platform: sun
  event: sunset
action:
  service: light.turn_on
  entity_id: light.entry
  data:
    rgb_color: [255, 0, 0]
    brightness: 62.5
    transition: 900